### ISSUE TITLE
Folded Stock/Quickdraw issue

### ISSUE THREAD

**Issue by VinierAardvark1** [RMC-Interops-Creators-Club/RMC-Interops#3]
The above attachments only speed up the deploy animation, but the firing delay remains the same like the original animation.
This may be the same issue with the Hecate II, even though its animation is faster than the Ultima Ratio.

**Comment by Jayrazer** [comment]
P226 does not have this issue.  It seems the that fire delay is based on the animation length + some defined delay somewhere.  My best guess is to snoop around weapon luas and see if anything points to a nextprimaryfire delay.
