### ISSUE TITLE
Error when holding G18C

### ISSUE THREAD

**Issue by VinierAardvark1** [RMC-Interops-Creators-Club/RMC-Interops#5]
[rmc interops] addons/rmc interops/lua/weapons/tacint_base/cl_viewmodel.lua:50: bad argument #1 to 'LookupBone' (string expected, got nil)
  1. LookupBone - [C]:-1
   2. DrawCustomModel - addons/rmc interops/lua/weapons/tacint_base/cl_viewmodel.lua:50
    3. unknown - addons/rmc interops/lua/weapons/tacint_base/cl_viewmodel.lua:6 (x1422)

**Comment by Jayrazer** [comment]
Cannot replicate.  Saw this error earlier and it has to do with legacy addons not reloading or luas not updating.  Is this still happening on your end?

**Comment by VinierAardvark1** [comment]
As of right now, yes. I've changed nothing in the code, so I'm confused on why this is happening
